package com.automation.Utility;


/**
 * @author Rakesh
 * Java interface for some constants
 *
 */
public interface AdvSchemaConstants {
	
	String XSDHeader = "<?xml version=\"1.0\"?>\n<!-- W3C Schema generated by Adeptia Editor  -->\n<xs:schema xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">\n";
	String XSDFooter = "</xs:schema>\n";
	String APPINFOHeader = "<xs:annotation>\n<xs:appinfo>\n";
	String APPINFOFooter = "</xs:appinfo>\n</xs:annotation>\n";
	String ComplexHeader = "<xs:complexType>\n";
	String ComplexFooter = "</xs:complexType>\n";
	String SequenceHeader = "<xs:sequence>\n";
	String SequenceFooter = "</xs:sequence>\n";
	String RootElementHeader = "<xs:element name=\"Root\">\n";
	String SheetElementAttribute = "<xs:attribute name=\"name\" type=\"xs:string\" use=\"required\"></xs:attribute>\n";
	String SectionElementAttribute = "<xs:attribute name=\"recordNumber\" type=\"xs:string\" use=\"required\"></xs:attribute>\n"
			+ "<xs:attribute name=\"sectiontype\" type=\"xs:string\" use=\"required\"></xs:attribute>\n";
	String SheetElementHeader = "<xs:element maxOccurs=\"unbounded\" minOccurs=\"1\" name=\"sheet\">\n";
	String ElementFooter = "</xs:element>\n";
	String RecordElementHeader = "<xs:element maxOccurs=\"unbounded\" minOccurs=\"0\" name=\"Record\">\n";
	String RecordElementValue = "<isRecordElement><![CDATA[true]]></isRecordElement>\n";
	String FormatTag = "<format><![CDATA[AAAAAA]]></format>\n";
	String DataModeTag = "<dataMode><![CDATA[plainText]]></dataMode>\n";
	
	
	String globalSheetName = "Schema Definition";
	String commentLineSeparator = "\n";
	String commentLineSeparator1 = "\r";
	String commentValueSeparator = "=";
	String regexPatternOfElement = "[^a-z A-Z]";
	String commentFieldsForExcel = "sectionOccurrenceLevel|Sheets|allowDiscontinousOrder|allowLessFields|processAllSheets|trimSpacesToReadFieldName"
			+ "|allowIgnoreCase|isRegexInSheet|SchemaDefinitionSheetName|sectionType|sectionName|elementName|occurrenceLevel|relativeRowRanges"
			+ "|relativeColumnRanges|ignoreBlankRows|uniqueFieldNames|endTokenIdentifier|primaryFieldNames|originalName|ignoreField|isSingleCell|fixedCellRange";
	
	String commentFieldsForPDF = "sectionName|sectionType|sectionIdentifier|nextRecordIdentifier|nextRecordValidationString|sectionEndTokenOperator"
			+ "|elementName|elementType|originalName|includeIdentifier|valueMatchOpertaor|numOfSectionPart|whichSectionPart|"
			+ "dataExtractionMode|endTokenIdentifier|recordValidationString";
	
	String commonSchemaDefinition="<XSDVersion><![CDATA[1]]></XSDVersion>\n<removeInvalidChar><![CDATA[false]]></removeInvalidChar>\n"
			+ "<manipulated><![CDATA[false]]></manipulated>\n<enclosedChar><![CDATA[ ]]></enclosedChar>\n"
			+ "<advanceExcel><![CDATA[false]]></advanceExcel>\n<mergeKey><![CDATA[ ]]></mergeKey>\n"
			+ "<isEncodedSheetName><![CDATA[true]]></isEncodedSheetName>\n<mergeCriteria><![CDATA[ ]]></mergeCriteria>\n"
			+ "<AdvExcelSchema><![CDATA[ ]]></AdvExcelSchema>\n"
			+ "<isAdvanceExcelSchema><![CDATA[true]]></isAdvanceExcelSchema>\n";
	String pdfSchemaDefinition="<Sheets><![CDATA[U2hlZXQx]]></Sheets>\n"
			+ "<allowDiscontinousOrder><![CDATA[false]]></allowDiscontinousOrder>\n<allowIgnoreCase><![CDATA[false]]></allowIgnoreCase>\n"
			+ "<allowLessFields><![CDATA[false]]></allowLessFields>\n"
			+ "<processAllSheets><![CDATA[false]]></processAllSheets>\n";
	

}
